services:

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8001:80"
    volumes:
      - ./:/var/www
      - ./_docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php

  php:
    container_name: php
    build:
      context: _docker/php
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:5432

  memcached:
    image: memcached:latest
    container_name: memcached
    ports:
      - "11211:11211"
    command:
      - memcached
      - -m 64
      - -v
    restart: unless-stopped

volumes:
  postgres_data: